import PDFDocument from "pdfkit"

export const generatePdf = (data) => {
	return new Promise((resolve, reject) => {
		try {
			const doc = new PDFDocument({
				size: "A4",
				margin: 45,
				bufferPages: true,
				info: {
					Author: "REZZAi",
					Title: data?.title || "REZZAi Document",
					Creator: "REZZAi Document Intelligence"
				}
			})

			const buffers = []
			doc.on("data", (chunk) => buffers.push(chunk))
			doc.on("end", () => resolve(Buffer.concat(buffers)))
			doc.on("error", (err) => reject(err))

			const PAGE_WIDTH = 595.28
			const MARGIN = 45
			const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2 // 505.28 pt

			const checkPageBreak = (neededHeight = 40) => {
				if (doc.y + neededHeight > 715) {
					doc.addPage()
					renderPageHeader()
				}
			}

			const renderPageHeader = () => {
				doc.font("Helvetica-Bold")
					.fontSize(8)
					.fillColor("#64748B")
					.text("REZZAi DOCUMENT INTELLIGENCE", MARGIN, 35, {
						width: CONTENT_WIDTH,
						align: "right",
						lineBreak: false
					})

				doc.rect(MARGIN, 48, CONTENT_WIDTH, 0.5).fill("#E2E8F0")
				doc.y = 60
			}

			// First Page Top Branding Header
			// Branded Capsule Badge
			doc.roundedRect(MARGIN, 40, 135, 22, 5).fill("#0F172A")
			doc.font("Helvetica-Bold")
				.fontSize(9)
				.fillColor("#DBFF4D")
				.text("✦ REZZAi DOCUMENT", MARGIN + 10, 47, { lineBreak: false })

			// Top Right Executive Label
			doc.font("Helvetica-Bold")
				.fontSize(8.5)
				.fillColor("#64748B")
				.text("EXECUTIVE BRIEFING", MARGIN, 47, {
					width: CONTENT_WIDTH,
					align: "right",
					lineBreak: false
				})

			// Header Divider
			doc.rect(MARGIN, 72, CONTENT_WIDTH, 0.75).fill("#E2E8F0")

			// Document Title
			doc.y = 90
			doc.font("Helvetica-Bold")
				.fontSize(22)
				.fillColor("#0F172A")
				.text(data?.title || "Document Title", MARGIN, doc.y, {
					width: CONTENT_WIDTH,
					lineGap: 4
				})

			// Subtitle
			if (data?.subtitle) {
				doc.moveDown(0.3)
				doc.font("Helvetica-Oblique")
					.fontSize(12)
					.fillColor("#475569")
					.text(data.subtitle, MARGIN, doc.y, {
						width: CONTENT_WIDTH,
						lineGap: 3
					})
			}

			// Decorative Accent Line below Title Block
			const titleDividerY = doc.y + 12
			doc.rect(MARGIN, titleDividerY, CONTENT_WIDTH, 1.5).fill("#E2E8F0")
			doc.rect(MARGIN, titleDividerY, 60, 1.5).fill("#2563EB")
			doc.y = titleDividerY + 20

			// Sections Loop
			if (Array.isArray(data?.sections)) {
				data.sections.forEach((section, index) => {
					checkPageBreak(45)

					const sectionY = doc.y

					// Section Accent Bar
					doc.roundedRect(MARGIN, sectionY + 1, 4, 18, 2).fill("#2563EB")

					// Section Heading
					doc.font("Helvetica-Bold")
						.fontSize(14)
						.fillColor("#0F172A")
						.text(`${index + 1}. ${section?.heading || "Section"}`, MARGIN + 14, sectionY, {
							width: CONTENT_WIDTH - 14
						})

					doc.y = doc.y + 6

					// Bullet Points
					if (Array.isArray(section?.points)) {
						section.points.forEach((point) => {
							checkPageBreak(25)

							const pointY = doc.y

							// Vector Bullet Dot
							doc.circle(MARGIN + 18, pointY + 5.5, 2.5).fill("#2563EB")

							// Bullet Point Text
							doc.font("Helvetica")
								.fontSize(10)
								.fillColor("#334155")
								.text(point, MARGIN + 28, pointY, {
									width: CONTENT_WIDTH - 28,
									lineGap: 3
								})

							doc.y = doc.y + 5
						})
					}

					doc.y = doc.y + 10
				})
			}

			// Footer & Page Numbers across all pages
			const range = doc.bufferedPageRange()
			for (let i = range.start; i < range.start + range.count; i++) {
				doc.switchToPage(i)

				// Bottom Divider at Y = 785
				doc.rect(MARGIN, 785, CONTENT_WIDTH, 0.5).fill("#CBD5E1")

				doc.font("Helvetica")
					.fontSize(8)
					.fillColor("#64748B")
					.text("Generated by REZZAi Document Intelligence", MARGIN, 793, {
						align: "left",
						lineBreak: false
					})

				doc.text(`Page ${i + 1} of ${range.count}`, MARGIN, 793, {
					width: CONTENT_WIDTH,
					align: "right",
					lineBreak: false
				})
			}

			doc.end()
		} catch (error) {
			reject(error)
		}
	})
}
