import PDFDocument from "pdfkit"

export const generatePdf = (data) => {
	return new Promise((resolve, reject) => {
		try {
			const doc = new PDFDocument({
				size: "A4",
				margin: 45,
				bufferPages: true,
				autoFirstPage: true,
				info: {
					Author: "REZZAi",
					Title: data?.title || "REZZAi Document",
					Creator: "REZZAi Document Intelligence"
				}
			})

			const buffers = []
			doc.on("data", (chunk) => buffers.push(chunk))
			doc.on("end", () => resolve(Buffer.concat(buffers)))
			doc.on("error", (err) => reject(err))

			const PAGE_WIDTH = 595.28
			const PAGE_HEIGHT = 841.89
			const MARGIN = 45
			const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2  // 505.28 pt
			const FOOTER_Y = PAGE_HEIGHT - 56              // 785.89 pt
			const BREAK_THRESHOLD = FOOTER_Y - 20          // stop content at ~765

			const checkPageBreak = (neededHeight = 40) => {
				if (doc.y + neededHeight > BREAK_THRESHOLD) {
					doc.addPage()
					renderPageHeader()
				}
			}

			const renderPageHeader = () => {
				doc.font("Helvetica-Bold")
					.fontSize(8)
					.fillColor("#64748B")
					.text("REZZAi DOCUMENT INTELLIGENCE", MARGIN, 35, {
						width: CONTENT_WIDTH,
						align: "right",
						lineBreak: false
					})

				doc.rect(MARGIN, 48, CONTENT_WIDTH, 0.5).fill("#E2E8F0")
				doc.y = 60
			}

			// ── First Page Branding ───────────────────────────────────────
			doc.roundedRect(MARGIN, 40, 135, 22, 5).fill("#0F172A")
			doc.font("Helvetica-Bold")
				.fontSize(9)
				.fillColor("#DBFF4D")
				.text("✦ REZZAi DOCUMENT", MARGIN + 10, 47, { lineBreak: false })

			doc.font("Helvetica-Bold")
				.fontSize(8.5)
				.fillColor("#64748B")
				.text("EXECUTIVE BRIEFING", MARGIN, 47, {
					width: CONTENT_WIDTH,
					align: "right",
					lineBreak: false
				})

			doc.rect(MARGIN, 72, CONTENT_WIDTH, 0.75).fill("#E2E8F0")

			// ── Document Title ────────────────────────────────────────────
			doc.y = 90
			doc.font("Helvetica-Bold")
				.fontSize(22)
				.fillColor("#0F172A")
				.text(data?.title || "Document Title", MARGIN, doc.y, {
					width: CONTENT_WIDTH,
					lineGap: 4
				})

			if (data?.subtitle) {
				doc.moveDown(0.3)
				doc.font("Helvetica-Oblique")
					.fontSize(12)
					.fillColor("#475569")
					.text(data.subtitle, MARGIN, doc.y, {
						width: CONTENT_WIDTH,
						lineGap: 3
					})
			}

			const titleDividerY = doc.y + 12
			doc.rect(MARGIN, titleDividerY, CONTENT_WIDTH, 1.5).fill("#E2E8F0")
			doc.rect(MARGIN, titleDividerY, 60, 1.5).fill("#2563EB")
			doc.y = titleDividerY + 20

			// ── Sections ──────────────────────────────────────────────────
			if (Array.isArray(data?.sections)) {
				data.sections.forEach((section, index) => {
					checkPageBreak(50)

					const sectionY = doc.y

					doc.roundedRect(MARGIN, sectionY + 1, 4, 18, 2).fill("#2563EB")

					doc.font("Helvetica-Bold")
						.fontSize(14)
						.fillColor("#0F172A")
						.text(`${index + 1}. ${section?.heading || "Section"}`, MARGIN + 14, sectionY, {
							width: CONTENT_WIDTH - 14
						})

					doc.y = doc.y + 6

					if (Array.isArray(section?.points)) {
						section.points.forEach((point) => {
							checkPageBreak(28)

							const pointY = doc.y

							doc.circle(MARGIN + 18, pointY + 5.5, 2.5).fill("#2563EB")

							doc.font("Helvetica")
								.fontSize(10)
								.fillColor("#334155")
								.text(String(point || ""), MARGIN + 28, pointY, {
									width: CONTENT_WIDTH - 28,
									lineGap: 3
								})

							doc.y = doc.y + 5
						})
					}

					doc.y = doc.y + 10
				})
			}

			// ── Footer on every page ──────────────────────────────────────
			// Use moveTo/lineTo + absolute coords with lineBreak:false
			// so PDFKit never auto-advances doc.y and creates a blank page
			const range = doc.bufferedPageRange()
			const totalPages = range.count

			for (let i = range.start; i < range.start + totalPages; i++) {
				doc.switchToPage(i)

				doc.moveTo(MARGIN, FOOTER_Y)
					.lineTo(MARGIN + CONTENT_WIDTH, FOOTER_Y)
					.lineWidth(0.5)
					.strokeColor("#CBD5E1")
					.stroke()

				doc.font("Helvetica")
					.fontSize(8)
					.fillColor("#64748B")
					.text("Generated by REZZAi Document Intelligence", MARGIN, FOOTER_Y + 8, {
						lineBreak: false
					})

				doc.font("Helvetica")
					.fontSize(8)
					.fillColor("#64748B")
					.text(`Page ${i + 1} of ${totalPages}`, MARGIN, FOOTER_Y + 8, {
						width: CONTENT_WIDTH,
						align: "right",
						lineBreak: false
					})
			}

			// Reset doc.y after footer loop — PDFKit auto-adds a blank page if
			// doc.y > page.maxY() when doc.end() is called. The footer text
			// pushes doc.y past the margin boundary on the last switched page.
			doc.y = MARGIN
			doc.end()
		} catch (error) {
			reject(error)
		}
	})
}
